### ISSUE TITLE
Add info about biopax properties mapped to RO to RO 

### ISSUE THREAD

**Issue by goodb** [goodb/noctua-exchange#2]
e.g. ro:has_input = bp:left.  ro:has_output = bp:right

**Comment by cmungall** [comment]
is this always true - how are bidirectional reactions represented in biopax?

**Comment by goodb** [comment]
Looks like its not so simple.  For a given Conversion reaction, need to check the range of the data property 'conversionDirection', for a catalytic Control event, need to check the range of CatalysisDirection, and for TemplateReaction templateDirection.  These direction properties are data properties with ranges conversionDirection: {"LEFT-TO-RIGHT"^^xsd:string , "REVERSIBLE"^^xsd:string , "RIGHT-TO-LEFT"^^xsd:string},  catalysisDirection:{"LEFT-TO-RIGHT"^^xsd:string , "RIGHT-TO-LEFT"^^xsd:string}, and templateDirection: {"FORWARD"^^xsd:string , "REVERSE"^^xsd:string} http://www.biopax.org/release/biopax-level3-documentation.pdf 

I don't see the concept of a 'bidirectional' reaction, I think that concept is captured as 'reversible'.  

More work needed here on converter, maybe another place where a rule-based approach would be nice.

**Comment by goodb** [comment]
Added a check for direction to reactome converter.  turns out everything they output is left to right so previous stuff would have worked okay.

**Comment by cmungall** [comment]
Ahh, I thought we could have some generic code that could work with RHEA biopax..

..but it turns out RHEA is using rdfs:comment in biopax 😢 

```
--
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Transport=false</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Direction=undefined</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Class of reactions=false</bp:COMMENT>
--
--
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Mapped=true</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Direction=bidirectional</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Formuled=true</bp:COMMENT>
--
--
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Transport=false</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Direction=right to left</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Class of reactions=false</bp:COMMENT>
--
--
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Formuled=true</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Direction=left to right</bp:COMMENT>
 <bp:COMMENT rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">RHEA:Polymerization=false</bp:COMMENT>
--
```

**Comment by goodb** [comment]
Yeah...  rather disappointing.  Noticed that they are using biopax level 2.  Perhaps if they were to re-implement their export in level 3 they might move all of this into a semantically accessible place.  The export also does not include the chebi mappings.  Have to get those somewhere else.

**Comment by goodb** [comment]
In case its useful, here is a small sample of the rhea export.  
[sample_full.owl.zip](https://github.com/goodb/noctua-exchange/files/1922448/sample_full.owl.zip)

**Comment by goodb** [comment]
Their rdf export looks more useful.  CHEBI mappings are there and less string parsing required. e.g. here is a reaction node

<rdf:Description rdf:about="http://rdf.rhea-db.org/10004">
        <rdfs:subClassOf rdf:resource="http://rdf.rhea-db.org/Reaction"/>
        <rh:id rdf:datatype="http://www.w3.org/2001/XMLSchema#long">10004</rh:id>
        <rh:accession>RHEA:10004</rh:accession>
        <rdfs:label>benzyl isothiocyanate = benzyl thiocyanate</rdfs:label>
        <rh:equation>benzyl isothiocyanate = benzyl thiocyanate</rh:equation>
        <rh:htmlEquation>benzyl isothiocyanate = benzyl thiocyanate</rh:htmlEquation>
        <rh:directionalReaction rdf:resource="http://rdf.rhea-db.org/10005"/>
        <rh:directionalReaction rdf:resource="http://rdf.rhea-db.org/10006"/>
        <rh:bidirectionalReaction rdf:resource="http://rdf.rhea-db.org/10007"/>
        <rh:status rdf:resource="http://rdf.rhea-db.org/Approved"/>
        <rh:isChemicallyBalanced rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</rh:isChemicallyBalanced>
        <rh:isTransport rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">false</rh:isTransport>
        <rh:ec rdf:resource="http://purl.uniprot.org/enzyme/5.99.1.1"/>
        <rh:side rdf:resource="http://rdf.rhea-db.org/10004_L"/>
</rdf:Description>

**Comment by goodb** [comment]
Without some more sophisticated mapping process the mapping of biopax properties to RO properties looks like a non-starter.
